m_server_name: "m_server"
m_server_addr: "127.0.0.1:14711"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14722"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14733"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4711"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4722"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4733"

#for cuda use 0,1,2,3 on Helios
train_device: "cuda:0" #tiger=1
infer_device: "cuda:1" #tiger=2
# infer_device: "cuda:0"
train_device_d: "cuda:2" #"cuda:2" tiger=1
infer_device_d: "cuda:1" #"cuda:3" tiger=0


#try from the smallest value on Helios
num_train_rollouts: 24 #72 #48 #24
num_train_workers: 24  #24

num_eval_rollouts: 12 #12
num_eval_workers: 2 #4

prepare_pool: ''

student_address1: ""
student_address2: ""
student_address3: ""
student_address4: ""
student_address5: ""
student_address6: ""
student_address7: ""
student_address8: ""
student_address9: ""
student_address10: ""
student_address11: ""
student_address12: ""
student_address13: ""
student_address14: ""
student_address15: ""
student_address16: ""


attacker_pool1: ""
attacker_pool2: ""
attacker_pool3: ""
attacker_pool4: ""
attacker_pool5: ""

attacker_checkpoint: "n"
defender_checkpoint: ""

trace_files: [
]
trace_limit: 200000000
legacy_trace_format: false

replay_buffer_size: 262144
replay_buffer_size_d: 262144
prefetch: 2

batch_size: 512
batch_size_d: 512
lr: 1e-4
lr_d: 1e-4
Gamma: 0.99
Gamma_d: 0.99
entropy_coeff: 0.03 # default 0.01
entropy_coeff_d: 0.1 # default 0.01
learning_starts: 65536
learning_starts_d: 65536
push_every_n_steps: 10
push_every_n_steps_d: 10

dual_clip: 3.0
eps_clip: 0.2 #default = 0.2

num_epochs: 15000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

trained_defender: false
use_attacker_pool: false

training_agents: "attacker-defender" # "defender" ,attacker-defender
training_mode: "static" # "dynamic"
attacker_train_epochs: 100
defender_train_epochs: 200

def_train_env: "balanced" # unbalanced, balanced, benign

comments: ""

defaults:
  - env_config: macta_env
  - model_config: transformer
