num_episodes: 20000
seed: 123 #123 1234 12345

###### Used in Tournament
attackers: [ 

            ["MACTA-attacker-4", ""]
            ]
detectors: [ 
            ["Locker", ""]
            ]

deterministic_policy: true

trace_file: ""
trace_files: [
    
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

    "",
    "",
    "",
    "",
    ]
trace_limit: 4000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
